### ISSUE TITLE
python get_data: 'metadata/bookshelves' is not a directory 

### ISSUE THREAD

**Issue by martingerlach** [pgcorpus/gutenberg#21]
When running python get_data.py I receive the following error message:

> mv: target 'metadata/bookshelves/' is not a directory

We should make sure that this folder exists already in the githb-repo

**Comment by fontclos** [comment]
is this happening in a start-from-scratch run ?

**Comment by fontclos** [comment]
ah, now I remember, I think this is not a problem anymore in the parse_bookshelves branch

**Comment by martingerlach** [comment]
Yes, this happened when running from scratch

**Comment by fontclos** [comment]
Ok I now remembered what happened: I did add a .dummy file some weeks ago, but then I also changed the dir name to bookshelves_html, cause I thought it was more clear. Then I forgot to push some commits from the branch I think. 

In any case, I've just pushed to master, this should be fixed. Can you try again from scratch to verify?

**Comment by martingerlach** [comment]
Yes, now it works when running from scratch.
Thanks.
