### ISSUE TITLE
rsync command fails on Windows 10

### ISSUE THREAD

**Issue by andreluizgit** [pgcorpus/gutenberg#30]
"To process all the data in the raw/ directory" even after run get_data I get only PG Metadata (title & author) but the raw files I couldn't get ... that is, the get_data get only metadata, it's correct?

`    # mirror dir
    parser.add_argument(
        "-m", "--mirror",
        help="Path to the mirror folder that will be updated via rsync.",
        default='data/.mirror/',
        type=str)  `

`   # raw dir
    parser.add_argument(
        "-r", "--raw",
        help="Path to the raw folder.",
        default='data/raw/',
        type=str)  `

I think that the rsync doesn't work : 

`Unexpected remote arg: aleph.gutenberg.org::gutenberg
rsync error: syntax or usage error (code 1) at main.c(1372) [sender=3.1.3]`

**Comment by fontclos** [comment]
doing `python get_data.py` should give you both the metadata and the raw files, so the issue could be related as you say to `rsync`. I just tried on a fresh clone and it wroked for me, so the server has not changed.

Could you share some system info? OS, python version, rsync version, etc

**Comment by andreluizgit** [comment]
Windows 10 Build 18855
python                    3.6.8
rsync  version 3.1.3  protocol version 31

Error when run get_data : 

> Unexpected remote arg: aleph.gutenberg.org::gutenberg

> rsync error: syntax or usage error (code 1) at main.c(1372) [sender=3.1.3]

**Comment by fontclos** [comment]
Ok, that might have to do with rsync's syntax on windows. Problem is, I don't have a windows machine to test this... the rsync command the script is running is:

```bash
rsync -amv --include */ --include [p123456789][g0123456789]*[.-][t0][x.]t[x.]*[t8] --exclude * aleph.gutenberg.org::gutenberg data/.mirror/
```
can you check if that works for you? it could be rsync or it could be related to how subprocess launches the it, I don't have experience with Windows

**Comment by andreluizgit** [comment]
rsync -amv --include */ --include [p123456789][g0123456789]*[.-][t0][x.]t[x.]*[t8] --exclude * aleph.gutenberg.org::gutenberg data/.mirror/
Unexpected remote arg: aleph.gutenberg.org::gutenberg
rsync error: syntax or usage error (code 1) at main.c(1372) [sender=3.1.3]

**Comment by fontclos** [comment]
Ok so its definitely an rsync problem: the version of rsync you're using on Windows differs from the one we use on unix. However differences are probably small so It should be possible to figure out how to change this line by reading `rsync --help` or `man rsync`.

**Comment by andreluizgit** [comment]
same Issue here : [https://www.linuxquestions.org/questions/linux-software-2/having-trouble-with-rsync-command-can-you-help-4175601064/](https://www.linuxquestions.org/questions/linux-software-2/having-trouble-with-rsync-command-can-you-help-4175601064/)

**Comment by fontclos** [comment]
Doing `python get_data.py` will download all books in PG by default, plus some metadata. That should be around 57K at the moment. 

Doing `python process_data.py` will process all books you have already downloaded. Always run these commands from the repository's top level directory.

**Comment by andreluizgit** [comment]
@fontclos I need this file : "_and will create a csv file with metadata (e.g. author, title, year, ...)._"

**Comment by fontclos** [comment]
this might help: https://zenodo.org/record/2422561#.XJu6ChO2kWo

**Comment by fontclos** [comment]
This one as well as #34 might be easy for someone with experience in rsync in Windows 10

**Comment by aegis1980** [comment]
There are a couple of things not 'windows friendly' - this rsync error is the first you'll hit.:

1.  subprocess calls to `rsync`, `wget `and` ln`. Windows needs [cwRsync](https://itefix.net/cwrsync), [wget ](https://eternallybored.org/misc/wget/) installed and  added to path, and use `mklink` instead of `ln`
2.  "\" vs "/" as a hardcoded file separator. Search for `"/"` and replace with `os.path.sep`

Working windows version a WIP - will push when/if I have it working. 
Alternatively (win10) run in ubuntu_on_windows.

**Comment by fontclos** [comment]
Thanks @aegis1980, a working windows version would be great! Still, I am not a windows user so I won't be able to maintain it. Perhaps for the moment ubuntu_on_windows is the simplest thing to do?

**Comment by fontclos** [comment]
closing and moving to  #37
