### ISSUE TITLE
get_data.py fails: ReadError

### ISSUE THREAD

**Issue by maxbry** [pgcorpus/gutenberg#32]
I cloned the repository, changed the paths, downloaded the data and the script fails with the following error:

    [...]
    # WARNING: file pg12273.txt.utf8 skipped due to duplication
    # WARNING: file pg8826.txt.utf8 skipped due to duplication
    # WARNING: file pg40075.txt.utf8 skipped due to duplication
    # WARNING: file pg57993.txt.utf8 skipped due to duplication
    # WARNING: file pg2947.txt.utf8 skipped due to duplication
    # WARNING: file pg4520.txt.utf8 skipped due to duplication
    # WARNING: file pg25525.txt.utf8 skipped due to duplication
    # WARNING: file pg3065.txt.utf8 skipped due to duplication
    Traceback (most recent call last):
      File "gutenberg/get_data.py", line 136, in <module>
        update=args.keep_rdf
      File "/projects/p070/p_scads/bryan/keras_max/gutenberg/src/metadataparser.py", line 71, in make_df_metadata
        md = readmetadata(path_xml, update=update)
      File "/projects/p070/p_scads/bryan/keras_max/gutenberg/src/metadataparser.py", line 118, in readmetadata
        for xml in getrdfdata(RDFFILES, update=update):
      File "/projects/p070/p_scads/bryan/keras_max/gutenberg/src/metadataparser.py", line 145, in getrdfdata
        with tarfile.open(RDFFILES) as archive:
      File "/sw/installed/Python/3.6.6-fosscuda-2018b/lib/python3.6/tarfile.py", line 1574, in open
        raise ReadError("file could not be opened successfully")
    tarfile.ReadError: file could not be opened successfully

**Comment by martingerlach** [comment]
Someone else also reported this issue via mail. The problem there was that access to PG is restricted from Germany (thus the failure to open the metadata file because it cannot be downloaded). 
Are you located in Germany?

**Comment by maxbry** [comment]
Yes I am

**Comment by martingerlach** [comment]
Ok, that explains. I think at the moment you cannot download this file while being in Germany.

You can manually download an older, 'frozen' version of the metadata file from the zenodo-repository (SPGC-metadata-2018-07-18.csv) https://doi.org/10.5281/zenodo.2422561
Put the file into the folder metadata/
Then you should hopefully not get the error that the file cannot be opened.

**Comment by YontiLevin** [comment]
had the same error when working on a remote server.
according to the gutenberg website - downloading to a server requires a different url.
this worked for me:
RDFURL = "http://gutenberg.readingroo.ms/cache/generated/feeds/rdf-files.tar.bz2"

**Comment by fontclos** [comment]
thanks @YontiLevin, implemented this in #35
