### ISSUE TITLE
indicate in README that SPGC-2018-07-18 doesn't contain full texts

### ISSUE THREAD

**Issue by bpshaver** [pgcorpus/gutenberg#33]
The SPGC-2018-07-18 download, all together, is quite large. Might be nice to note that it doesn't include `data/texts/`, in case (for example) people are following along in the  `tutorial_01_how-to-read-a-book-metadata.ipynb`.

**Comment by fontclos** [comment]
Hi @bpshaver, thanks for the suggestion, that was indeed not very clear in the readme. I just modified the readme, hopefully it is more clear now.
